# Imposta il layout
layout splits

# 1. Sinistra
launch fish -c "weathr"

# 2. Destra Alto (31%)
launch --location=vsplit --bias=31 fish -c "peaclock --config-dir ~/.config/peaclock"

# 3. Destra Basso (60%)
# Mettiamo sleep 0.5 per far caricare le dimensioni della finestra a Wayland prima di disegnare l'albero!
launch --location=hsplit --bias=60 fish -c "sleep 0.5; /usr/bin/cbonsai -S"
